export const currency = '$';
export const currentYear = new Date().getFullYear();
export const developedByLink = '#';
export const developedBy = 'Data Insights Office';
export const contactUs = 'info@dataoffice.com';
export const buyLink = '';
export const basePath = '';
export const DEFAULT_PAGE_TITLE = 'Nasiye | TaskPlus Admin Dashboard';
export const colorVariants = ['primary', 'secondary', 'success', 'danger', 'warning', 'info', 'dark', 'light', 'link'];